### ISSUE TITLE
How to include mct when running as R package?

### ISSUE THREAD

**Issue by ke2rchan** [labsyspharm/naivestates#52]
Hello! I am using naivestates on R and was able to follow the "example usage" codes to get the probability outputs. However, I am looking for the output of cell ID to Cell state (The output from when using naivestates on MCMicro, using the naivestates-model parameter). 

Was wondering how can i incorporate the mct.csv part when running on R? Any help would be appreciated! :)

**Comment by ke2rchan** [comment]
also, will i be able to generate the UMAP as well? (when running as an R package)

**Comment by ArtemSokolov** [comment]
Hi @ke2rchan,

I recommend stepping through `main.R` to understand how the tool is used by MCMICRO.

In particular, here is where `mct.csv` is read and used: https://github.com/labsyspharm/naivestates/blob/master/main.R#L97-L109
At the end of this code block, the matrix `Z` will map cell IDs to cell states.

UMAP generation is done here: https://github.com/labsyspharm/naivestates/blob/master/main.R#L142-L158
It uses the matrix `Y` which contains the [probability of expression](https://github.com/labsyspharm/naivestates/blob/master/main.R#L89-L90) computed earlier.

**Comment by ke2rchan** [comment]
that helped a lot!! thank you so much! was able to run it fully :)
